# Generated by Django 3.0.5 on 2020-04-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('had', models.IntegerField()),
            ],
            options={
                'db_table': 'storage',
            },
        ),
    ]
