# Generated by Django 3.0.5 on 2020-04-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sell_number', models.IntegerField()),
                ('date', models.TimeField()),
            ],
            options={
                'db_table': 'sale',
            },
        ),
        migrations.RemoveField(
            model_name='storage',
            name='id',
        ),
        migrations.AlterField(
            model_name='storage',
            name='book_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
